#!/bin/sh
# Gradle wrapper stub — real wrapper will be generated by Android Studio
echo "Gradle wrapper not present. Open the project in Android Studio to generate it."
echo "Alternatively, install Gradle 8.9+ and run: gradle wrapper"
